### ISSUE TITLE
freeswitch-404.conf should be fusionpbx-404.conf

### ISSUE THREAD

**Issue by daniel-lucio** [fusionpbx/fusionpbx-install.sh#134]
Just to make a difference when it is FreeSWITCH normal log or a FusionPBX artifice.

**Comment by markjcrane** [comment]
Its a matter of your point of view.

- It named this way because its read from a freeswitch log.
- Alternatively it is generated by FusionPBX dialplan so could go with the name fusionpbx-404.conf

 I can see it both from and really it could go either way.

**Comment by markjcrane** [comment]
I've decided to change it.
