### ISSUE TITLE
[ERR] mod_lua.cpp:203 

### ISSUE THREAD

**Issue by lamnh77** [fusionpbx/fusionpbx-install.sh#160]
Hi Fusionpbx,
I installed on debian 8, LXC CT Proxmox 5, Please help.
After installed error from freeswitch log:

2018-04-04 08:46:33.965744 [ERR] mod_lua.cpp:203 .../share/freeswitch/scripts/resources/functions/config.lua:22: module 'resources.config' not found:
	no field package.preload['resources.config']
	no file '/usr/share/freeswitch/scripts/resources/config.lua'
	no file '/usr/local/lib/lua/5.2/resources/config.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.2/resources/config.so'
	no file '/usr/lib/lua/5.2/resources/config.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './resources/config.so'
	no file '/usr/local/lib/lua/5.2/resources.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.2/resources.so'
	no file '/usr/lib/lua/5.2/resources.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './resources.so'
stack traceback:
	[C]: in function 'require'
	.../share/freeswitch/scripts/resources/functions/config.lua:22: in function 'load_config'
	.../share/freeswitch/scripts/resources/functions/config.lua:26: in main chunk
	[C]: in function 'require'
	/usr/share/freeswitch/scripts/app.lua:28: in main chunk
2018-04-04 08:46:33.965757 [ERR] mod_lua.cpp:271 LUA script parse/execute error!
2018-04-04 08:46:33.966496 [ERR] mod_lua.cpp:203 .../share/freeswitch/scripts/resources/functions/config.lua:22: module 'resources.config' not found:
	no field package.preload['resources.config']
	no file '/usr/share/freeswitch/scripts/resources/config.lua'
	no file '/usr/local/lib/lua/5.2/resources/config.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.2/resources/config.so'
	no file '/usr/lib/lua/5.2/resources/config.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './resources/config.so'
	no file '/usr/local/lib/lua/5.2/resources.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.2/resources.so'
	no file '/usr/lib/lua/5.2/resources.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './resources.so'
stack traceback:
	[C]: in function 'require'
	.../share/freeswitch/scripts/resources/functions/config.lua:22: in function 'load_config'
	.../share/freeswitch/scripts/resources/functions/config.lua:26: in main chunk
	[C]: in function 'require'
	/usr/share/freeswitch/scripts/app.lua:28: in main chunk
2018-04-04 08:46:33.966508 [ERR] mod_lua.cpp:271 LUA script parse/execute error!
2018-04-04 08:46:33.966659 [INFO] switch_core.c:2436 
FreeSWITCH Version 1.6.20-37-987c9b9~64bit (-37-987c9b9 64bit)

FreeSWITCH Started
Max Sessions [1000]
Session Rate [30]
SQL [Enabled]
2018-04-04 08:46:33.970450 [ERR] mod_lua.cpp:203 .../share/freeswitch/scripts/resources/functions/config.lua:22: module 'resources.config' not found:
	no field package.preload['resources.config']
	no file '/usr/share/freeswitch/scripts/resources/config.lua'
	no file '/usr/local/lib/lua/5.2/resources/config.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.2/resources/config.so'
	no file '/usr/lib/lua/5.2/resources/config.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './resources/config.so'
	no file '/usr/local/lib/lua/5.2/resources.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.2/resources.so'
	no file '/usr/lib/lua/5.2/resources.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './resources.so'
stack traceback:
	[C]: in function 'require'
	.../share/freeswitch/scripts/resources/functions/config.lua:22: in function 'load_config'
	.../share/freeswitch/scripts/resources/functions/config.lua:26: in main chunk
	[C]: in function 'require'
	/usr/share/freeswitch/scripts/app.lua:28: in main chunk
2018-04-04 08:46:33.970467 [ERR] mod_lua.cpp:271 LUA script parse/execute error!
2018-04-04 08:46:33.970635 [DEBUG] mod_event_socket.c:2961 Socket up listening on 127.0.0.1:8021
2018-04-04 08:46:33.970750 [DEBUG] switch_loadable_module.c:735 Chat Thread Started
2018-04-04 08:46:33.970773 [DEBUG] switch_loadable_module.c:735 Chat Thread Started
2018-04-04 08:46:33.971133 [INFO] switch_time.c:615 Clock synchronized to system time.

**Comment by markjcrane** [comment]
Your issue is the same as someone on IRC so I assume it might be you. If so then re-install and it worked. Is it resolved?

**Comment by lamnh77** [comment]
Hi @markjcrane ,

Thanks you, I had try 5 times, Error because https://packages.sury.org/php/ it's alot of "wget: unable to resolve host address 'packages.sury.org'".

It's work now.

**Comment by markjcrane** [comment]
Reported that it's working so clI sing the issue.
