### ISSUE TITLE
Error on login into FusionPBX, insert postgres error on installation in debian 8

### ISSUE THREAD

**Issue by dacarr** [fusionpbx/fusionpbx-install.sh#167]
On the default install on debian 8 the resources/finish.sh file drops php 'PDOException' with a postgres 'ERROR:  invalid input syntax for uuid: "" '

**Comment by markjcrane** [comment]
Does it throw this error on something and the install still completes and its working?

**Comment by markjcrane** [comment]
This issue has been fixed. It caused no side affects but still nice to get fixed.
