### ISSUE TITLE
FusionPBX/FreeSwitch Installation in RHEL

### ISSUE THREAD

**Issue by vjchavan4** [fusionpbx/fusionpbx-install.sh#172]
Hi Friends, 
Good Day. Am about to start my project, where I have given a task to install the FreeSwitch along with FusionPBX for GUI. Can you throw some light on this topic please.

what all pre-requisite needed before installation and procedure to install in RHEL. Thank for your kindness

**Comment by markjcrane** [comment]
The CentOS script is the closest to RHEL it is a good guide. It should be enough information combined with some search engine requests.
