### ISSUE TITLE
[IMPROVEMENT] Small security fix in nginx config

### ISSUE THREAD

**Issue by samael33** [fusionpbx/fusionpbx-install.sh#180]
Idea is to replace all .htaccess/.db file rules with

# Disable viewing all . (.htaccess, .git, etc...) except .well-known
	location ~ /\.(?!well-known\/) {
        deny all;
    }

Cause .git directory is also could be accessed by nginx, it's not critical, but just to be more secure.

**Comment by markjcrane** [comment]
.git is not a security risk at all we are on github so this is all public information.

**Comment by markjcrane** [comment]
Its more likely custom software that you don't want to share to the web server.

**Comment by markjcrane** [comment]
Did add the following a while ago. So closing the issue.

location ~ /.git/ {
		deny all;
}
