### ISSUE TITLE
Debian 9 Stretch Install appears to work, but useful Freeswitch modules are missing

### ISSUE THREAD

**Issue by danry25** [fusionpbx/fusionpbx-install.sh#196]
It appears the following modules are not installed when running the Debian script on [Stretch](https://gist.github.com/danry25/54e847502e3ae9f705d36de53343052f) instead of [Jessie](https://gist.github.com/danry25/fa6a05ffd339c934189be30eae98b900). The links I inserted show a list of packages after a fresh install on either OS (though the Stretch install has a few extras like htop & tmux that I manually installed), the notable differences to me are the following missing packages on Debian 9:
```
freeswitch-meta-codecs
freeswitch-mod-amr
freeswitch-mod-amrwb
freeswitch-mod-b64
freeswitch-mod-bv
freeswitch-mod-codec2
freeswitch-mod-dahdi-codec
freeswitch-mod-distributor
freeswitch-mod-g723-1
freeswitch-mod-g729
freeswitch-mod-h26x
freeswitch-mod-isac
freeswitch-mod-mp4v
freeswitch-mod-silk
freeswitch-mod-skypopen
freeswitch-mod-skypopen-dbg
freeswitch-mod-spandsp
freeswitch-mod-theora
```

Many of these look to be automatically installed as part of a metapackage, freeswitch-meta-codecs, which depends on the packages listed below that don't exist in the Freeswitch 1.6 Stretch repo.

```
The following packages have unmet dependencies:
 freeswitch-meta-codecs : Depends: freeswitch-mod-bv (= 1.6.20-1~stretch+1) but it is not installable
                          Depends: freeswitch-mod-codec2 (= 1.6.20-1~stretch+1) but it is not installable
                          Depends: freeswitch-mod-dahdi-codec (= 1.6.20-1~stretch+1) but it is not installable
                          Depends: freeswitch-mod-mp4v (= 1.6.20-1~stretch+1) but it is not installable
                          Depends: freeswitch-mod-silk (= 1.6.20-1~stretch+1) but it is not installable
```

After taking a quick look at the [Freeswitch 1.8 Package List](http://files.freeswitch.org/repo/deb/freeswitch-1.8/dists/stretch/main/binary-amd64/Packages), the missing packages are available there. Seems the Debian install script needs some tuning for Stretch, I will try using the Freeswitch 1.8 repo when installing, presuming that works expect a pull request with that change when the OS is detected as Stretch?

Open to suggestions on that last bit (about switching to Freeswitch 1.8), let me know if there is a different way this should be resolved!

**Comment by markjcrane** [comment]
Accepted a pull request on the topic.
