### ISSUE TITLE
different between package-systemd.sh and source-systemd.sh

### ISSUE THREAD

**Issue by barsara** [fusionpbx/fusionpbx-install.sh#204]
Hi 

This script is great. We like it.

We try to use this script to build fusionpbx, but we build freeswitch with source.
In resources/switch/package-systemd.sh, we found the "systemctl start freeswitch" in the last line.
But in resources/switch/source-systemd.sh, there is no "systemctl start freeswitch"

Could anyone tell us why? Thanks in advance.

**Comment by markjcrane** [comment]
Package is used more than the source code. So it has had more attention. So not much to tell it was missed. Fixed https://github.com/fusionpbx/fusionpbx-install.sh/commit/3dbea76a1d84970ef1b4f117b06d31c817988d3f

**Comment by barsara** [comment]
Hi~

Thanks for your reply. Now we can relax.
We thought there is a technological reason for no "systemctl start freeswitch" in source-systemd.sh,

Thanks.
