### ISSUE TITLE
Actual apt options

### ISSUE THREAD

**Issue by denser** [fusionpbx/fusionpbx-install.sh#211]
> W: --force-yes is deprecated, use one of the options starting with --allow instead.
Need to fix it.

**Comment by markjcrane** [comment]
Provide a link to documentation showing deprecated and another link to the alternative.

**Comment by markjcrane** [comment]
The --allow commands I saw don't really look that relevant.
--allow-unauthenticated , --allow-downgrades , --allow-remove-essential , --allow-change-held-packages

Will likely go back to one of these  -y, --yes, --assume-yes

**Comment by markjcrane** [comment]
Tried it with -y and its working fine without --force-yes and so I removed all instances of --force-yes.
You should no longer see the deprecated message.
