### ISSUE TITLE
incorrect filename 

### ISSUE THREAD

**Issue by Ahrongreenberg** [fusionpbx/fusionpbx-install.sh#215]
the files in fusionpbx-install.sh/debian/resources/backup/ are missing the .sh on the end of filename

**Comment by markjcrane** [comment]
They aren’t required in /etc/cron.daily

**Comment by Ahrongreenberg** [comment]
So update the docs at https://docs.fusionpbx.com/en/latest/getting_started/backup.html#crontab
for people who whish copy paste the script.
