### ISSUE TITLE
fresh install Debian 9 and centos 7 with fusionpbx 4.4 on master branch, got error with insert into relative "v_user_groups"

### ISSUE THREAD

**Issue by QuangLeHong** [fusionpbx/fusionpbx-install.sh#228]
when finish.sh was call to end installation, it got  issued with console as below.
--------------------------------
On Centos 7.5 x64
--------------------------------
.........
ALTER ROLE
ALTER ROLE
INSERT 0 1
PHP Warning:  Invalid argument supplied for foreach() in /var/www/fusionpbx/app/devices/app_defaults.php on line 96
Warning: Invalid argument supplied for foreach() in /var/www/fusionpbx/app/devices/app_defaults.php on line 96
PHP Warning:  Invalid argument supplied for foreach() in /var/www/fusionpbx/app/devices/app_defaults.php on line 96

Warning: Invalid argument supplied for foreach() in /var/www/fusionpbx/app/devices/app_defaults.php on line 96
PHP Warning:  Invalid argument supplied for foreach() in /var/www/fusionpbx/app/devices/app_defaults.php on line 96

Warning: Invalid argument supplied for foreach() in /var/www/fusionpbx/app/devices/app_defaults.php on line 96
PHP Warning:  Invalid argument supplied for foreach() in /var/www/fusionpbx/app/devices/app_defaults.php on line 96

Warning: Invalid argument supplied for foreach() in /var/www/fusionpbx/app/devices/app_defaults.php on line 96
PHP Warning:  Invalid argument supplied for foreach() in /var/www/fusionpbx/app/devices/app_defaults.php on line 96

Warning: Invalid argument supplied for foreach() in /var/www/fusionpbx/app/devices/app_defaults.php on line 96
PHP Warning:  Invalid argument supplied for foreach() in /var/www/fusionpbx/app/devices/app_defaults.php on line 96
Warning: Invalid argument supplied for foreach() in /var/www/fusionpbx/app/devices/app_defaults.php on line 96
PHP Warning:  Illegal string offset 'dir' in /var/www/fusionpbx/app/number_translations/app_defaults.php on line 43

Warning: Illegal string offset 'dir' in /var/www/fusionpbx/app/number_translations/app_defaults.php on line 43
INSERT 0 1
ERROR:  relation "v_user_groups" does not exist
LINE 1: insert into v_user_groups (user_group_uuid, domain_uuid, gro...
.....

----------------------------------------------------------------
On Debian 9
--------------------------------------------------------------
on Debian9 , when the finish.sh was called, it is error :
........
ALTER ROLE
ALTER ROLE
INSERT 0 1
ERROR: relation "v_user_groups" does not exist
LINE 1: insert into v_user_groups (user_group_uuid, domain_uuid, gro...

issues found on:
Fusionpbx : 4.4
freeswitch: 1.8.5 x64
branch: master

**Comment by QuangLeHong** [comment]
on Debian9 , when the finish.sh was called, it is error :
........
ALTER ROLE
ALTER ROLE
INSERT 0 1
ERROR: relation "v_user_groups" does not exist
LINE 1: insert into v_user_groups (user_group_uuid, domain_uuid, gro...

**Comment by QuangLeHong** [comment]
Hi Team 
The Installation was broken just on Feb 9 2019, i did install successfully and all worked just before Feb 9 commits. Now nothing works. These issues are critical since i  can not do fresh install again for my sip servers.

**Comment by markjcrane** [comment]
Sorry that only works on master branch. I'll get it fixed right away.

**Comment by markjcrane** [comment]
It should be fixed now please update your install script and try it again.

**Comment by markjcrane** [comment]
I believe the fix I did two days ago worked for 4.4 branch and then this morning I did more work to fix the master branch install. Tested on Debian 9 for worked on stable and master branch.
