### ISSUE TITLE
Error php-fpm7.1 at end of install-script in debian 9

### ISSUE THREAD

**Issue by trideeindhoven** [fusionpbx/fusionpbx-install.sh#230]
I am using the installscript under Debian 9 and at the very end of the installscript i get an error as seen below.
FusionPBX seems to run ok, but i think it may be nice to fix it.

creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

Success. You can now start the database server using:

    /usr/lib/postgresql/11/bin/pg_ctl -D /var/lib/postgresql/11/main -l logfile start

Ver Cluster Port Status Owner    Data directory              Log file
11  main    5432 down   postgres /var/lib/postgresql/11/main /var/log/postgresql/postgresql-11-main.log
update-alternatives: using /usr/share/postgresql/11/man/man1/postmaster.1.gz to provide /usr/share/man/man1/postmaster.1.gz (postmaster.1.gz) in auto mode
Setting up postgresql (11+199.pgdg90+1) ...
Processing triggers for systemd (232-25+deb9u8) ...
W: --force-yes is deprecated, use one of the options starting with --allow instead.
CREATE DATABASE
CREATE DATABASE
CREATE ROLE
CREATE ROLE
GRANT
GRANT
GRANT
Failed to restart php7.1-fpm.service: Unit php7.1-fpm.service not found.
ALTER ROLE
ALTER ROLE
INSERT 0 1
INSERT 0 1
INSERT 0 1

Installation has completed.
   Use a web browser to login.

**Comment by ruslanguns** [comment]
As I said in IRC my guess is that the script has a wrong version since the installed is 7.0 for PHP. And regarding the flag --flag-yes my thought is that it's just has to be modified by the new one.

**Comment by trideeindhoven** [comment]
Hi Ruslán,

I will look into this as i feel uncomfortable setting up a new 
productionserver with errors during installation :)
Thanks for the feedback.
Will inform you if and when fixed.
Kind regards,

Jeroen J.A.W. Hermans
Managing Director Epsys
........................................................................
Epsys | Piuslaan 197 | 5643 BA | Eindhoven
T +31 (0)40 281 71 67
M +31 (0)6 14 797 418
E j.hermans@epsys.nl
........................................................................

**Comment by markjcrane** [comment]
I just rewrote  part of the the script removed --force-yes. Used sury repo so we can use PHP 7.1. Moved install of PHP out of nginx.sh an into php.sh something I have wanted to do for a while. Removed unnecessary service restarts in finish.sh.  To upgrade to php 7.1 on current install do the following.

Debian 8 or 9
cd /usr/src/fusionpbx-install.sh/debian/resources/upgrade
git pull
./php.sh
