### ISSUE TITLE
postgresql 9.4 bdr

### ISSUE THREAD

**Issue by vishalmpai** [fusionpbx/fusionpbx-install.sh#236]
Hello Everyone

I am trying to install fusionpbx using database repo  2ndquadrant seems the key has been expired

W: GPG error: http://packages.2ndquadrant.com jessie-2ndquadrant InRelease: The following signatures were invalid: KEYEXPIRED 1553321615 KEYEXPIRED 1553321615 KEYEXPIRED 1553321615

pub   2048R/AA7A6805 2015-03-24 [expired: 2019-03-23]
      Key fingerprint = 855A F5C7 B897 6564 17FA  73D6 5D94 1908 AA7A 6805
uid                  BDR Apt Signing Key for 2ndQuadrant <packagers@2ndquadrant.com>

Can anyone have the same issue in Postgres 9.4 bdr new installation

Thanks
Vishal

**Comment by markjcrane** [comment]
This needs to be done by 2ndquadrant.
