### ISSUE TITLE
Problem with the installer

### ISSUE THREAD

**Issue by DigiDaz** [fusionpbx/fusionpbx-install.sh#34]
The install fails due to permission denied on a couple of files.

There is no execute permission on some files in /usr/src/fusionpbx-install.sh/debian/resources/switch

-rw-r--r-- 1 root root  130 Aug 18 22:10 conf-copy.sh
-rwxr-xr-x 1 root root 1012 Aug 18 22:10 package-all.sh
-rwxr-xr-x 1 root root  688 Aug 18 22:10 package-master-all.sh
-rwxr-xr-x 1 root root 2171 Aug 18 22:10 package-master.sh
-rwxr-xr-x 1 root root  254 Aug 18 22:10 package-permissions.sh
-rwxr-xr-x 1 root root 2484 Aug 18 22:10 package-release.sh
-rw-r--r-- 1 root root  329 Aug 18 22:10 package-systemd.sh
drwxr-xr-x 2 root root 4096 Aug 18 22:10 source
-rwxr-xr-x 1 root root 2818 Aug 18 22:10 source-master.sh
-rwxr-xr-x 1 root root  191 Aug 18 22:10 source-permissions.sh
-rwxr-xr-x 1 root root 3587 Aug 18 22:10 source-release.sh
-rw-r--r-- 1 root root  252 Aug 18 22:10 source-systemd.sh

**Comment by Ceus** [comment]
Did you follow the instructions on the website and was this a fresh install?

`apt-get update && apt-get upgrade -y --force-yes
apt-get install -y --force-yes git
cd /usr/src
git clone https://github.com/fusionpbx/fusionpbx-install.sh.git
chmod 755 -R /usr/src/fusionpbx-install.sh
cd /usr/src/fusionpbx-install.sh/debian
./install.sh`

**Comment by markjcrane** [comment]
I have attempted to fix this a week or two ago with git commands and then committed them apparently this didn't solve the problem. I will try again.

**Comment by markjcrane** [comment]
git update-index --chmod=+x conf-copy.sh
git update-index --chmod=+x package-systemd.sh
git update-index --chmod=+x source-systemd.sh

**Comment by markjcrane** [comment]
Pulled new source with and permissions show the file is executable.
git clone https://github.com/fusionpbx/fusionpbx-install.sh.git
ls -lh
total 52K
-rwxr-xr-x 1 root root  130 Sep  4 14:56 conf-copy.sh
-rwxr-xr-x 1 root root 1012 Sep  4 14:56 package-all.sh
-rwxr-xr-x 1 root root  688 Sep  4 14:56 package-master-all.sh
-rwxr-xr-x 1 root root 2.6K Sep  4 14:56 package-master.sh
-rwxr-xr-x 1 root root  254 Sep  4 14:56 package-permissions.sh
-rwxr-xr-x 1 root root 2.9K Sep  4 14:56 package-release.sh
-rwxr-xr-x 1 root root  329 Sep  4 14:56 package-systemd.sh
drwxr-xr-x 2 root root 4.0K Sep  4 14:56 source
-rwxr-xr-x 1 root root 3.0K Sep  4 14:56 source-master.sh
-rwxr-xr-x 1 root root  191 Sep  4 14:56 source-permissions.sh
-rwxr-xr-x 1 root root 3.8K Sep  4 14:56 source-release.sh
-rwxr-xr-x 1 root root  252 Sep  4 14:56 source-systemd.sh
-rwxr-xr-x 1 root root  744 Sep  4 14:56 source-to-package.sh
