### ISSUE TITLE
installation script breaks xrdp.

### ISSUE THREAD

**Issue by LeeJohnAnderson** [fusionpbx/fusionpbx-install.sh#41]
I ran the install script on a fresh debian 8 image from the MS azure gallery. I then installed xrdp and was able to rdp to the machine. after running the installer, connection attempts to the  machine fail.

**Comment by markjcrane** [comment]
So there is likely a dependency conflict.

**Comment by markjcrane** [comment]
The recommended install is to use debian 8 minimal install with SSH. In order to use xrdp you would need a desktop interface which isn't needed. If you do install that then upgrading the operating system takes longer because a lot more is installed. Closing the issue because if you follow the recommended install this wouldn't be a concern.

**Comment by LeeJohnAnderson** [comment]
would anyone have any suggestions (given the experience on this board) of how one might begin to troubleshoot?

**Comment by markjcrane** [comment]
You would look at the install script and install the dependencies one or more at a time and test xrdp to see at what point it breaks. You could also comment pieces of the install script and test it a piece at a time.

**Comment by LeeJohnAnderson** [comment]
Thank you mark.

**Comment by DigiDaz** [comment]
If you insist on having a desktop interface which is such an amateur way of doing it, ie installing a desktop environment to do what is essentially cli, then editing fusionpbx-install.sh/debian/resources/iptables.sh and inserting a line similar to:

iptables -A INPUT -j ACCEPT -p tcp --dport 3389 -m comment --comment "rdp"

That may be the wrong port but it was definitely old MS RDP port

**Comment by LeeJohnAnderson** [comment]
DigiDaz, many thanks for the suggestion. Apologies for being an amateur but we all start somewhere.

**Comment by markjcrane** [comment]
Good point didn't think about the fact its very likely to be iptables firewall blocking it.
After running the command suggested by DigiDaz run this one to save it so that it will still be there after you reboot.
dpkg-reconfigure iptables-persistent

**Comment by DigiDaz** [comment]
LeeJohnAnderson, if you truly are a beginner then take the time to learn how to use SSH to connect and nano as an editor as mcrane suggested. Its far more rewarding, much, much faster and does not need any of the desktop resources.
