### ISSUE TITLE
autoconf

### ISSUE THREAD

**Issue by whenry** [fusionpbx/fusionpbx-install.sh#45]
debian Install script is missing apt-get package for autoconf

**Comment by mafoo** [comment]
this is dealt with in the source-master.sh - https://github.com/fusionpbx/fusionpbx-install.sh/blob/master/debian/resources/switch/source-master.sh#L3
and source-release.sh - https://github.com/fusionpbx/fusionpbx-install.sh/blob/master/debian/resources/switch/source-release.sh#L3
