### ISSUE TITLE
Domain Edit Causes Hang

### ISSUE THREAD

**Issue by whenry** [fusionpbx/fusionpbx-install.sh#47]
When we update a domain setting, such as Name, Enabled or Description.  This is not the meta-data section, but the core domain settings at the top of domain edit screen

IE
goto URL to edit a domain, for example
1) https://iqventures.bphone.io/core/domain_settings/domain_edit.php?id=5354512e-fd0b-42af-909a-xxxxxxxx
2) Change a setting
3) Click Save

The system will then hang until nginx is stopped and started

**Comment by markjcrane** [comment]
Its unlikely that it hung php5-fpm is busy and working. Unless you have a database lock you can it to see if it has.
tail -f /var/log/postgresql/postgresql-9.4-main.log

**Comment by markjcrane** [comment]
When you update a domain it currently runs app defaults. I will optimize this further in the future. Sorry I've been busy my schedule should clear up the end of next week.

**Comment by markjcrane** [comment]
Not an issue with the install script closing this issue.
