### ISSUE TITLE
incorrect package-master.sh ^M characters

### ISSUE THREAD

**Issue by CrezZ** [fusionpbx/fusionpbx-install.sh#48]
File package-master.sh has ^M end of lines (Windows EOL), and ubuntu (14.04) cannot run this and has incorrect filenames after running. 
sed -e "s/^M//" package-master.sh > package-master.sh.new 
and then replace old file wit new one can resolve it

**Comment by markjcrane** [comment]
This should be fixed CrezZ if it comes up again please make sure to report it.
