### ISSUE TITLE
Fresh Installer Not Working

### ISSUE THREAD

**Issue by dmccabe-kinex** [fusionpbx/fusionpbx-install.sh#55]
I have installed a fresh copy of Debian 8 x64 with only SSH and the basic package per the instructions. Everything in the walkthrough works fine, up until you run ./install.sh. It fails to get packages stating that they are unavailable and there is no alternative. Please advise if this is a Debian Repository issue, or if the installer script is having problems.

**Comment by Len-PGH** [comment]
do you have something like this in your sources.list?  Which packages are unavailable?

 cat /etc/apt/sources.list

deb http://non-us.debian.org/debian-non-US stable/non-US main contrib non-free
deb http://http.us.debian.org/debian stable main contrib non-free
deb http://security.debian.org/ jessie/updates main
deb-src http://security.debian.org/ jessie/updates main

**Comment by markjcrane** [comment]
Other option the date is wron on your server.
Run the date command to verify the date.
date

If it is wrong then fix the date or report back for some help to fix it.

**Comment by dmccabe-kinex** [comment]
I uncovered the issue. The script was calling for several download sources that A) were not added to my sources.list by default just to get to the repositories, and B) my firewall was blocking from downloading due to FTP and miscellaneous port restrictions. I was able to get it, and working with FusionPBX now. Thanks!
