### ISSUE TITLE
login to fusionpbx web interface failed after install.sh multiple times execution

### ISSUE THREAD

**Issue by erxspin** [fusionpbx/fusionpbx-install.sh#60]
When ./install.sh script runs multiple times multiple records in tables v_domains, v_users, v_group_users are inserted and login with admin account is failed.

It seems that ./debian/resources/finish.sh script needs some modifications.

**Comment by erxspin** [comment]
1. Added sql check for multiple rows before insert new
2. Do insert, update and/or delete rows after this check

What behaviour is preferable by default ?

**Comment by erxspin** [comment]
This is previous commit but with another parent commit isolated to indepedent branch

**Comment by erxspin** [comment]
I tested this changes with Ubuntu 16.x and it works as planned

**Comment by erxspin** [comment]
Also I tested it with Debian 8.x

**Comment by erxspin** [comment]
This issue can be solved by pull request #63

**Comment by erxspin** [comment]
What line must be chosen when there are multiple lines in v_domains and v_users already ?

             domain_uuid              | domain_parent_uuid |  domain_name   | domain_enabled | domain_description
--------------------------------------+--------------------+----------------+----------------+--------------------
 1303fe38-f3d6-4fea-8486-cd0eb3b751e4 |                    | ip.add.re.ss | false          |
 32af4924-c7e0-4f93-97f8-b65cd755ad69 |                    | ip.add.re.ss | true           |
 530ab595-5672-4eb2-9925-3d4c6724afbd |                    | ip.add.re.ss | false          |
 5e1708aa-b125-4176-bc0c-76102a1bbe0f |                    | ip.add.re.ss | false          |
 6bc8bf10-b091-4772-8649-f5b783d097de |                    | ip.add.re.ss | true          |
 77f2a421-eef4-44a3-ba33-9b476d3987d0 |                    | ip.add.re.ss | false          |
 a7796a75-b461-4241-882c-1cf9fa8d5bc3 |                    | ip.add.re.ss | false          |
 d31eb919-764b-432f-bb03-faab6566af08 |                    | ip.add.re.ss | false          |
 ef2957e5-2756-4e1e-a125-88de1fb4f42e |                    | ip.add.re.ss | true          |
 fa25ad11-31aa-4b8e-b284-a49b9f7d0f09 |                    | ip.add.re.ss | true          |
(10 rows)

**Comment by markjcrane** [comment]
Should prevent this by re-using the matching domain rather than inserting it again. Then there shouldn't be duplicates to disable.

**Comment by erxspin** [comment]
It works exactly as proposed with additional checks before select, insert or update.

If there is no row at all for domain with domain_enabled=true check then script inserts a row with new domain_uuid.

If there is only one row for domain with domain_enabled=true check then script uses found domain_uuid subsequently.

If there are duplicate rows already for domain with domain_enabled=true check then script chooses first row from  filtered list and uses found domain_uuid. Other rows from this list will be "disabled" with domain_enabled=false.

Password will be updated to new one because there is no possibility to figure out what is current password.

It doesn't matter how duplicate domains was created before ( inserted, updated, etc ) if you leave it without touch then login to fusionpbx web interface with "admin@this_domain" account will be failed with chance (N-1)/N where N is duplicate rows count.

**Comment by erxspin** [comment]
Of course these changes in script logic will prevent duplicates when there is 0 or 1 row.

**Comment by Bchudasama** [comment]
erxspin in your earlier comments you said if the image is install multiple times with same IP address will create the domainuuid. but if we use doffrent ip for instal  will it still do that

**Comment by markjcrane** [comment]
Your case of duplicate domains with the same name was created by the install script being run multiple times. If the install script re-uses the existing domain rather then adding a duplicate domain then the case you are working to prevent won't even exist.

**Comment by erxspin** [comment]
I think that script with proposed changes will not prevent creation of multiple domains with different ip ...
I haven't checked that situation yet.

**Comment by erxspin** [comment]
@Bchudasama - Can you send an output of changed script with domains uuids ?

You can get it here

https://github.com/erxspin/fusionpbx-install.sh/tree/BugFix-Multiple-records-in-db

``
$ cd /usr/src
``

``
$ git clone https://github.com/erxspin/fusionpbx-install.sh
``

``
$ cd fusionpbx-install.sh
``

``
$ git checkout "BugFix-Multiple-records-in-db"
``

``
$ ./install.sh
``

**Comment by markjcrane** [comment]
I've rewritten the script and clear the database for new installs which solves this problem.

**Comment by erxspin** [comment]
Cutting the Gordian knot

**Comment by erxspin** [comment]
I will reopen this issue

**Comment by markjcrane** [comment]
New install drops public schema and the re adds it. So duplicate domain is not possible.
