### ISSUE TITLE
take codename of Debian like system for constructing repo list

### ISSUE THREAD

**Issue by erxspin** [fusionpbx/fusionpbx-install.sh#68]
Why we don't take codename of Debian like system from 'lsb_release -c' command output ?
And after that use it for constructing repo source line ?

**Comment by erxspin** [comment]
=============================================================
# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
# lsb_release -c
Codename:       jessie
=============================================================
# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
# lsb_release -c
Codename:       xenial
=============================================================
# cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
# lsb_release -c
Codename:       trusty
=============================================================
# cat /etc/os-release
NAME="Ubuntu"
VERSION="12.04.5 LTS, Precise Pangolin"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu precise (12.04.5 LTS)"
VERSION_ID="12.04"
# lsb_release -c
Codename:       precise
=============================================================

**Comment by markjcrane** [comment]
I believe this was addressed with one of the pull requests I accepted.

**Comment by erxspin** [comment]
Not yet merged into master only in my local devel branch because of rewriting

**Comment by erxspin** [comment]
And before continuing work it requires merging pull requests #72 ( merged ) and may be #75 ( ready to go )
