### ISSUE TITLE
modify install.sh to support Ubuntu and Centos

### ISSUE THREAD

**Issue by erxspin** [fusionpbx/fusionpbx-install.sh#72]

**Comment by erxspin** [comment]
No problems with Ubuntu check but there is no lsb_release command in Centos by default

``
$ ls -la /etc/*release
``
-rw-r--r--. 1 root root 27 May 19  2016 /etc/centos-release
lrwxrwxrwx. 1 root root 14 Jul  6  2016 /etc/redhat-release -> centos-release
lrwxrwxrwx. 1 root root 14 Jul  6  2016 /etc/system-release -> centos-release

http://kerryitnote.blogspot.com/2016/08/how-to-check-centos-version.html

**Comment by erxspin** [comment]
``
$ lsb_release -a
``

LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
Distributor ID: CentOS
Description:    CentOS release 6.8 (Final)
Release:        6.8
Codename:       Final

**Comment by markjcrane** [comment]
Committed

**Comment by erxspin** [comment]
Source

https://www.freedesktop.org/software/systemd/man/os-release.html

Some OS detection code is here

https://github.com/KittyKatt/screenFetch/blob/master/screenfetch-dev

**Comment by markjcrane** [comment]
This script is GPL we cannot take anything from this script. If you must remove it.
https://github.com/KittyKatt/screenFetch/blob/master/screenfetch-dev

**Comment by markjcrane** [comment]
As far as this goes I would like the operating system detection which was added by another developer in its own file to be used as an include.

**Comment by erxspin** [comment]
It is not issue, my changes is original work.

I only search the web for ``lsb_release -a`` outputs to correctly address linux distributions names returned and its codenames in scripts checking routines.

Almost all of it - Debian, Ubuntu, CentOS, Fedora - I checked myself.

I can not check RHEL only. So I just find this dist name "RedHatEnterpriseServer" on the web.

**Comment by erxspin** [comment]
I make decision to rely on lsb_release output.
May be it would be simpler to rely on /etc/os-release.
