### ISSUE TITLE
login to fusionpbx web interface failed after install.sh multiple times execution - part 2

### ISSUE THREAD

**Issue by erxspin** [fusionpbx/fusionpbx-install.sh#79]
Continuation of issue #60

**Comment by erxspin** [comment]
There are almost same situation as before in #60.

Multiple execution -> multiple domains -> login to fusionpbx web interface failed.

More details of issue are revealed after testing with Debian 8.x and Ubuntu 16.04.x

If you remembered password of admin account for first created domain then you can login with it.

You cannot login with freshly generated password because it linked with new domain with same name.

There is a little chance to login successfully if domain_uuid of new domain is fetched before other existed domains with same name.

**Comment by erxspin** [comment]
This commands was executed two times.

``
$ wget https://raw.githubusercontent.com/fusionpbx/fusionpbx-install.sh/master/install.sh -O install.sh && sh install.sh
``

Log of first execution -> I can login with new password

...
DROP SCHEMA
CREATE SCHEMA
CREATE DATABASE
CREATE DATABASE
CREATE ROLE
CREATE ROLE
GRANT
GRANT
GRANT
Correct CPU and Operating System detected
ALTER ROLE
ALTER ROLE
INSERT 0 1
INSERT 0 1
INSERT 0 1


Installation has completed.

   Use a web browser to login.
      domain name: https://aaa.bbb.ccc.ddd
      username: admin
      password: jBwN4u2FCfSTJq2

   The domain name in the browser is used by default as part of the authentication.
   If you need to login to a different domain then use username@domain.
      username: admin@aaa.bbb.ccc.ddd
...

Log of second execution -> I cannot login with new password

...
DROP SCHEMA
CREATE SCHEMA
ERROR:  database "fusionpbx" already exists
ERROR:  database "freeswitch" already exists
ERROR:  role "fusionpbx" already exists
ERROR:  role "freeswitch" already exists
GRANT
GRANT
GRANT
Correct CPU and Operating System detected
ALTER ROLE
ALTER ROLE
INSERT 0 1
INSERT 0 1
INSERT 0 1


Installation has completed.

   Use a web browser to login.
      domain name: https://aaa.bbb.ccc.ddd
      username: admin
      password: 8Mh2Eoin1eUhMzsy

   The domain name in the browser is used by default as part of the authentication.
   If you need to login to a different domain then use username@domain.
      username: admin@aaa.bbb.ccc.ddd
...

**Comment by erxspin** [comment]
There 2 active domains and 2 "admin" users after that.

**Comment by erxspin** [comment]
@markjcrane 
> New install drops public schema and the re adds it. So duplicate domain is not possible.

But it was not dropped with current version of script. Details are above.

**Comment by markjcrane** [comment]
This has been fixed all that I needed to add was -d fusionpbx.

**Comment by erxspin** [comment]
Tested, works ok

...

NOTICE:  drop cascades to 95 other objects
DETAIL:  drop cascades to table v_access_controls
drop cascades to table v_access_control_nodes
drop cascades to table v_call_block
drop cascades to table v_call_broadcasts
drop cascades to table v_call_center_agents
drop cascades to table v_call_center_queues
drop cascades to table v_call_center_tiers
drop cascades to table v_call_flows
drop cascades to table v_conference_centers
drop cascades to table v_conference_rooms
drop cascades to table v_conference_sessions
drop cascades to table v_conference_session_details
drop cascades to table v_conference_controls
drop cascades to table v_conference_control_details
drop cascades to table v_conference_profiles
drop cascades to table v_conference_profile_params
drop cascades to table v_conferences
drop cascades to table v_conference_users
drop cascades to table v_contacts
drop cascades to table v_contact_addresses
drop cascades to table v_contact_phones
drop cascades to table v_contact_notes
drop cascades to table v_contact_users
drop cascades to table v_contact_groups
drop cascades to table v_contact_settings
drop cascades to table v_contact_relations
drop cascades to table v_contact_emails
drop cascades to table v_contact_urls
drop cascades to table v_contact_times
drop cascades to table v_destinations
drop cascades to table v_devices
drop cascades to table v_device_lines
drop cascades to table v_device_settings
drop cascades to table v_device_keys
drop cascades to table v_device_profiles
drop cascades to table v_device_vendors
drop cascades to table v_device_vendor_functions
drop cascades to table v_device_vendor_function_groups
drop cascades to table v_dialplans
drop cascades to table v_dialplan_details
drop cascades to table v_clips
drop cascades to table v_emails
drop cascades to table v_extensions
drop cascades to table v_extension_users
drop cascades to table v_fax
drop cascades to table v_fax_users
drop cascades to table v_fax_files
drop cascades to table v_fax_logs
drop cascades to table v_fax_tasks
drop cascades to table v_follow_me
drop cascades to table v_follow_me_destinations
drop cascades to table v_gateways
drop cascades to table v_ivr_menus
drop cascades to table v_ivr_menu_options
drop cascades to table v_meetings
drop cascades to table v_meeting_users
drop cascades to table v_modules
drop cascades to table v_music_on_hold
drop cascades to table v_phrases
drop cascades to table v_phrase_details
drop cascades to table v_pin_numbers
drop cascades to table v_recordings
drop cascades to table v_ring_groups
drop cascades to table v_ring_group_destinations
drop cascades to table v_ring_group_users
drop cascades to table v_services
drop cascades to table v_settings
drop cascades to table v_sip_profiles
drop cascades to table v_sip_profile_domains
drop cascades to table v_sip_profile_settings
drop cascades to table v_vars
drop cascades to table v_voicemail_greetings
drop cascades to table v_voicemails
drop cascades to table v_voicemail_messages
drop cascades to table v_voicemail_destinations
drop cascades to table v_voicemail_options
drop cascades to table v_xml_cdr
drop cascades to table v_apps
drop cascades to table v_databases
drop cascades to table v_default_settings
drop cascades to table v_languages
drop cascades to table v_countries
drop cascades to table v_domains
drop cascades to table v_domain_settings
drop cascades to table v_menus
drop cascades to table v_menu_items
drop cascades to table v_menu_item_groups
drop cascades to table v_menu_languages
drop cascades to table v_notifications
drop cascades to table v_software
drop cascades to table v_users
drop cascades to table v_groups
drop cascades to table v_group_users
drop cascades to table v_group_permissions
drop cascades to table v_user_settings
DROP SCHEMA
CREATE SCHEMA
ERROR:  database "fusionpbx" already exists
ERROR:  database "freeswitch" already exists
ERROR:  role "fusionpbx" already exists
ERROR:  role "freeswitch" already exists
GRANT
GRANT
GRANT
Correct CPU and Operating System detected
ALTER ROLE
ALTER ROLE
INSERT 0 1
INSERT 0 1
INSERT 0 1


Installation has completed.

   Use a web browser to login.
      domain name: https://aaa.bbb.ccc.ddd
      username: admin
      password: pDRGoNn0wpeI421

   The domain name in the browser is used by default as part of the authentication.
   If you need to login to a different domain then use username@domain.
      username: admin@aaa.bbb.ccc.ddd

**Comment by erxspin** [comment]
Log of first time execution of new version of install script under Debian 8.7 amd64
( for historical purposes )

...
psql: FATAL:  database "fusionpbx" does not exist
psql: FATAL:  database "fusionpbx" does not exist
CREATE DATABASE
CREATE DATABASE
CREATE ROLE
CREATE ROLE
GRANT
GRANT
GRANT
Correct CPU and Operating System detected
ALTER ROLE
ALTER ROLE
INSERT 0 1
INSERT 0 1
INSERT 0 1


Installation has completed.

   Use a web browser to login.
      domain name: https://aaa.bbb.ccc.ddd
      username: admin
      password: SwNTpapsBBRDEWfV

   The domain name in the browser is used by default as part of the authentication.
   If you need to login to a different domain then use username@domain.
      username: admin@aaa.bbb.ccc.ddd

**Comment by markjcrane** [comment]
Yes it's a minor issue with no harm other than log of it. Maybe not the permanent solution. But it works.
