### ISSUE TITLE
Enhancement - Replace echo by printf

### ISSUE THREAD

**Issue by erxspin** [fusionpbx/fusionpbx-install.sh#80]
http://askubuntu.com/questions/467747/which-is-better-printf-or-echo

http://unix.stackexchange.com/questions/65803/why-is-printf-better-than-echo/65819#65819

Solution is this code

```
echo() {
  if [ "$#" -gt 0 ]; then
     printf %s "$1"
     shift
  fi
  if [ "$#" -gt 0 ]; then
     printf ' %s' "$@"
  fi
  printf '\n'
}
```

**Comment by erxspin** [comment]
More info

https://www.gnu.org/software/autoconf/manual/autoconf-2.66/html_node/Limitations-of-Builtins.html

**Comment by markjcrane** [comment]
This suggestion appears to look okay. Do we have any known issues right now of echo causing a problem?

**Comment by erxspin** [comment]
Tested under FreeBSD 10.3 amd64 - work ok for /bin/sh, not works for /bin/csh

Tested under CentOS 7.3 amd64 - work ok for /bin/sh and /bin/bash

**Comment by erxspin** [comment]
Tested under Debian 8.7 amd64 - work ok for /bin/sh and /bin/bash

**Comment by markjcrane** [comment]
I read what you said and linked to. However I'm not seeing any issues with 'echo' on Debian, FreeBSD, or CentOS. Maybe I missed something read it sometime ago. From what I've seen \n has not been a problem. We aren't using \n I don't think in any of the scripts but I could be wrong. Still your function is interesting and I plan to refer back to it as a resource. Leaving this issue open for a few more days to await a response for you to explain why using 'echo' is a problem that we need to fix.

**Comment by erxspin** [comment]
I think that there are lines with possibly "unsafe" usage of "echo" ...

Because of "read" not so safest usage and may be there are more "not properly filtered" usage of env variables ...

```
echo "      domain name: https://$domain_name"
echo "      username: $user_name"
echo "      password: $user_password"
```

```
echo "      username: $user_name@$domain_name";
```

```
read -p "Enter all Node IP Addresses: " nodes
...
read -p 'Create Group (true/false): ' group_create
if [ .$group_create = .true ]; then
        read -p 'Enter this Nodes Address: ' node_1;
else
        read -p 'Join using node already in group: ' node_1;
        read -p 'Enter this Nodes Address: ' node_2;
fi
...

...
echo "Create Group: $group_create";
echo "All Node IP Addresses: $nodes";
if [ .$group_create = .true ]; then
        echo "This Nodes Address: $node_1";
else
        echo "Join using node in group: $node_1;"
        echo "This Node Address: $node_2";
fi
```

```
echo "Using version $SWITCH_VERSION"
```

```
echo "DEFAULT_VERSIONS+=pgsql=$database_version" >> /etc/make.conf
```

...

**Comment by erxspin** [comment]
This info might be useful ...

https://dev.to/thiht/shell-scripts-matter

https://www.shellcheck.net/
