### ISSUE TITLE
ARM 64 bit kernel and 32 bit userland install from packages

### ISSUE THREAD

**Issue by erxspin** [fusionpbx/fusionpbx-install.sh#81]
From IRC channel

> ``<DigiDaz> mcrane: Just installed on an Odroid C2, it was horrible :)``
> ``<@mcrane> 8:31 AM <DigiDaz> Its using a 64bit kernel with a 32 bit userland``

**Comment by erxspin** [comment]
From @DigiDaz
``As simply testing for armv7l doesn't work for PI3 as it is armv8l but will happily run 32bit armv7l packages.``

**Comment by markjcrane** [comment]
I have an odroid c2 so I'll take a look too.

**Comment by DigiDaz** [comment]
Just to let you know, the line for my repo needs to be:

deb [arch=armhf] http://repo.sip247.com/debian/freeswitch-stable-armhf/ jessie main

**Comment by markjcrane** [comment]
Thanks for the note.

**Comment by erxspin** [comment]
@DigiDaz
@markjcrane
and others

I need output of these commands from your ARM systems to analyze

``ls -la /etc/*release``
``cat /etc/*release``
``lsb_release -a``
``uname -a``

**Comment by erxspin** [comment]
This issue is linked with issue #76 "ARM install now broken"

**Comment by markjcrane** [comment]
ARM install was fixed by DigiDaz.
