### ISSUE TITLE
missing cd "$(dirname "$0")" in package-all.sh

### ISSUE THREAD

**Issue by cofirazak** [fusionpbx/fusionpbx-install.sh#84]
Hi, in file fusionpbx-install.sh/debian/resources/switch/package-all.sh there is no line that changes dir to script dir like this:
#move to script directory so all relative paths work
cd "$(dirname "$0")"
That's the reason why the include files can't be included

**Comment by markjcrane** [comment]
Thanks for pointing this out it has been fixed.
