### ISSUE TITLE
centos missing username and password

### ISSUE THREAD

**Issue by AIFun** [fusionpbx/fusionpbx-install.sh#94]
The following six lines have been remove in finish.sh on last commit

```
echo "   Use a web browser to login."
echo "      domain name: https://$domain_name"
echo "      username: $user_name"
echo "      password: $user_password"
```

Is this  a mistake?

**Comment by markjcrane** [comment]
This script was started by another developer based on an earlier version of my Debian script.

**Comment by markjcrane** [comment]
I have fixed the problem and simplified the CentOS install script. The changes make the scripts more consistent with Debian and FreeBSD installs scripts I created. Testing it now.

**Comment by markjcrane** [comment]
Seems to be working now. Let me know if you have any problems.
