### ISSUE TITLE
Install under freebsd doesnt work

### ISSUE THREAD

**Issue by roema** [fusionpbx/fusionpbx-install.sh#97]
Freeswitch compilation error.

> 
src/switch_rtp.c:1525:8: error: taking the absolute value of unsigned type 'unsigned int' has no effect [-Werror,-Wabsolute-value]
                        if (abs(rtp_session->ts - rtp_session->last_write_ts) > rtp_session->samples_per_interval 
                            ^
src/switch_rtp.c:1525:8: note: remove the call to 'abs' since unsigned values cannot be negative
                        if (abs(rtp_session->ts - rtp_session->last_write_ts) > rtp_session->samples_per_interval 
                            ^~~
src/switch_rtp.c:8024:7: error: taking the absolute value of unsigned type 'uint32_t' (aka 'unsigned int') has no effect
      [-Werror,-Wabsolute-value]
                if (abs(ts_delta) > rtp_session->samples_per_second * 2) {
                    ^
src/switch_rtp.c:8024:7: note: remove the call to 'abs' since unsigned values cannot be negative
                if (abs(ts_delta) > rtp_session->samples_per_second * 2) {

>

**Comment by markjcrane** [comment]
Please report build problems to FreeSWITCH jira. 

I have just changed the code from using git to get the latest source to using this:
fetch https://files.freeswitch.org/freeswitch-releases/freeswitch-1.6.17.zip

Testing the install again to make sure it works. I'm pretty confident this approach will be more dependable as the file will not change until the next official release.

**Comment by roema** [comment]
Is it possible to take the Freeswitch version from pkg -> 1.6.13_2 ?

**Comment by roema** [comment]
Sorry, doesnt work.

**Comment by roema** [comment]
Okay, i have the solution.
Use the git versions 1.6
- pkg install gcc49
- setenv CC gcc49
- setenv CFLAGS '-Wno-error -std=gnu99'
- ./bootstrap.sh -j

**Comment by markjcrane** [comment]
Added what you suggested and still get the same error on latest git release branch.
pkg_install gcc49
set CC gcc49
set CFLAGS '-Wno-error -std=gnu99'

**Comment by roema** [comment]
If you add it to the shell script (/bin/sh), you schould do it with export
try:

pkg install gcc49

export CC=gcc49
export CFLAGS='-Wno-error -std=gnu99'

**Comment by markjcrane** [comment]
I was missing the equals sign. I added that 'export' and other CFLAGS from the FreeBSD port and it worked.

**Comment by roema** [comment]
Perfect!
